# -*- coding: utf-8 -*-
"""Trabalho_Computacao1_ThiagoTavaresBraga.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FqJsyqk6mYJa_Jhh3tMI97AvfWJABXNK
"""

import random

def desenhar_tabuleiro(tabuleiro):
    # Desenha o tabuleiro de jogo na tela.
    print('-------------')
    for i in range(3):
        print('|', tabuleiro[i][0], '|', tabuleiro[i][1], '|', tabuleiro[i][2], '|')
        print('-------------')

def verificar_vitoria(tabuleiro, jogador):
    # Verifica linhas, colunas e diagonais, para analisar o jogador específico que venceu o jogo.
    for i in range(3):
        if all(tabuleiro[i][j] == jogador for j in range(3)) or \
           all(tabuleiro[j][i] == jogador for j in range(3)):
            return True
    if all(tabuleiro[i][i] == jogador for i in range(3)) or \
       all(tabuleiro[i][2-i] == jogador for i in range(3)):
        return True
    return False

def verificar_empate(tabuleiro):
    # Verifica linhas, colunas e diagonais, para analisar se houve um empate no jogo.
    for linha in tabuleiro:
        for elemento in linha:
            if elemento == ' ':
                return False
    return True

def jogada_jogador(tabuleiro):
    # Explicar que a função permite que o jogador humano faça uma jogada e como a entrada é validada.
    while True:
        try:
            linha = int(input("Digite a linha (1-3): ")) - 1
            coluna = int(input("Digite a coluna (1-3): ")) - 1
            if 0 <= linha <= 2 and 0 <= coluna <= 2 and tabuleiro[linha][coluna] == ' ':
                return linha, coluna
            else:
                print("Jogada inválida. Tente novamente.")
        except ValueError:
            print("Entrada inválida. Digite um número inteiro.")

def jogada_computador(tabuleiro, dificuldade):
    # Detalhar as diferentes estratégias de jogo para o computador em cada nível de dificuldade.
    if dificuldade == 1:
        return jogada_computador_facil(tabuleiro)
    elif dificuldade == 2:
        return jogada_computador_medio(tabuleiro)

def jogada_computador_facil(tabuleiro):
    # Realiza uma jogada aleatória para o computador.
    while True:
        linha = random.randint(0, 2)
        coluna = random.randint(0, 2)
        if tabuleiro[linha][coluna] == ' ':
            return linha, coluna

def jogada_computador_medio(tabuleiro):
    # Prioriza o centro
    if tabuleiro[1][1] == ' ':
        return 1, 1

    # Prioriza cantos
    cantos = [(0, 0), (0, 2), (2, 0), (2, 2)]
    random.shuffle(cantos)
    for linha, coluna in cantos:
        if tabuleiro[linha][coluna] == ' ':
            return linha, coluna

    # Escolhe uma posição aleatória
    return jogada_computador_facil(tabuleiro)

def main():
    # Descrever o fluxo principal do programa, incluindo a escolha do modo de jogo e a alternância entre os turnos.
    print("Bem-vindo ao Jogo da Velha!")

    tabuleiro = [[' ' for _ in range(3)] for _ in range(3)]

    modo_jogo = input("Digite 1 para jogar contra o computador ou 2 para jogar com um amigo: ")

    if modo_jogo == '1':
        # Modo contra o computador
        jogador = 'X'
        computador = 'O'
        dificuldade = int(input("Escolha a dificuldade (1-Fácil, 2-Médio): "))

        while True:
            desenhar_tabuleiro(tabuleiro)

            if jogador == 'X':
                linha, coluna = jogada_jogador(tabuleiro)
            else:
                linha, coluna = jogada_computador(tabuleiro, dificuldade)

            tabuleiro[linha][coluna] = jogador

            # Verificando vitória e empate
            if verificar_vitoria(tabuleiro, jogador):
                desenhar_tabuleiro(tabuleiro)
                print(f"O jogador {jogador} venceu!")
                break
            elif verificar_empate(tabuleiro):
                desenhar_tabuleiro(tabuleiro)
                print("Empate!")
                break

            jogador = computador if jogador == 'X' else 'X'

    elif modo_jogo == '2':
        # Modo multiplayer
        jogador1 = input("Nome do jogador 1 (X): ")
        jogador2 = input("Nome do jogador 2 (O): ")
        jogador_atual = jogador1

        while True:
            desenhar_tabuleiro(tabuleiro)

            print(f"Vez de {jogador_atual}")
            linha, coluna = jogada_jogador(tabuleiro)

            tabuleiro[linha][coluna] = 'X' if jogador_atual == jogador1 else 'O'

            # Verificando vitória e empate
            if verificar_vitoria(tabuleiro, 'X'):
              desenhar_tabuleiro(tabuleiro)
              print(f"O jogador {jogador1} venceu!")
              break
            elif verificar_vitoria(tabuleiro, 'O'):
              desenhar_tabuleiro(tabuleiro)
              print(f"O jogador {jogador2} venceu!")
              break
            elif verificar_empate(tabuleiro):
              desenhar_tabuleiro(tabuleiro)
              print("Empate!")
              break


            jogador_atual = jogador2 if jogador_atual == jogador1 else jogador1

    else:
        print("Opção inválida. Por favor, digite 1 ou 2.")

if __name__ == "__main__":
    main()